In [53]:
import pandas as pd

In [54]:
df = pd.read_csv(r"D:\05_PROJECTS\supplychain\Supply Chain Intelligence Platform for Forecasting, Logistics, and Operational Analytics\DataCoSupplyChainDataset.csv",encoding="latin1")

In [55]:
df.head()
pd.set_option('display.max_columns', None)
df

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,XXXXXXXXX,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.750000,0.29,1,327.750000,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2/03/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,XXXXXXXXX,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.750000,-0.80,1,327.750000,311.359985,-249.089996,South Asia,Rajastán,PENDING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,XXXXXXXXX,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.750000,-0.80,1,327.750000,309.720001,-247.779999,South Asia,Rajastán,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,XXXXXXXXX,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.750000,0.08,1,327.750000,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,XXXXXXXXX,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.750000,0.45,1,327.750000,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,EE. UU.,XXXXXXXXX,Maria,1005,Peterson,XXXXXXXXX,Home Office,NY,1322 Broad Glade,11207.0,7,Fan Shop,40.640930,-73.942711,Pacific Asia,Shanghái,China,1005,1/16/2016 3:40,26043,1004,0.000000,0.00,65177,399.980011,0.10,1,399.980011,399.980011,40.000000,Eastern Asia,Shanghái,CLOSED,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,EE. UU.,XXXXXXXXX,Ronald,9141,Clark,XXXXXXXXX,Corporate,CA,7330 Broad Apple Moor,93304.0,7,Fan Shop,35.362545,-119.018700,Pacific Asia,Hirakata,Japón,9141,1/16/2016 1:34,26037,1004,4.000000,0.01,65161,399.980011,-1.55,1,399.980011,395.980011,-613.770019,Eastern Asia,Osaka,COMPLETE,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,EE. UU.,XXXXXXXXX,John,291,Smith,XXXXXXXXX,Corporate,CT,97 Burning Landing,6010.0,7,Fan Shop,41.629959,-72.967155,Pacific Asia,Adelaide,Australia,291,1/15/2016 21:00,26024,1004,8.000000,0.02,65129,399.980011,0.36,1,399.980011,391.980011,141.110001,Oceania,Australia del Sur,PENDING,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,Puerto Rico,XXXXXXXXX,Mary,2813,Smith,XXXXXXXXX,Consumer,PR,2585 Silent Autumn Landing,725.0,7,Fan Shop,18.213350,-66.370575,Pacific Asia,Adelaide,Australia,2813,1/15/2016 20:18,26022,1004,12.000000,0.03,65126,399.980011,0.48,1,399.980011,387.980011,186.229996,Oceania,Australia del Sur,PENDING_PAYMENT,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,Puerto Rico,XXXXXXXXX,Andrea,7547,Ortega,XXXXXXXXX,Consumer,PR,697 Little Meadow,725.0,7,Fan Shop,18.290380,-66.370613,Pacific Asia,Nagercoil,India,7547,1/15/2016 18:54,26018,1004,16.000000,0.04,65113,399.980011,0.44,1,399.980011,383.980011,168.949997,South Asia,Tamil Nadu,PENDING_PAYMENT,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [56]:
duplicates = df[df.duplicated()]
print(duplicates)

Empty DataFrame
Columns: [Type, Days for shipping (real), Days for shipment (scheduled), Benefit per order, Sales per customer, Delivery Status, Late_delivery_risk, Category Id, Category Name, Customer City, Customer Country, Customer Email, Customer Fname, Customer Id, Customer Lname, Customer Password, Customer Segment, Customer State, Customer Street, Customer Zipcode, Department Id, Department Name, Latitude, Longitude, Market, Order City, Order Country, Order Customer Id, order date (DateOrders), Order Id, Order Item Cardprod Id, Order Item Discount, Order Item Discount Rate, Order Item Id, Order Item Product Price, Order Item Profit Ratio, Order Item Quantity, Sales, Order Item Total, Order Profit Per Order, Order Region, Order State, Order Status, Order Zipcode, Product Card Id, Product Category Id, Product Description, Product Image, Product Name, Product Price, Product Status, shipping date (DateOrders), Shipping Mode]
Index: []

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 128.4 MB

In [58]:
df['Customer Lname'] = df['Customer Lname'].fillna(
    df['Customer Lname'].mode()[0]
)

In [59]:
print(df['Customer Lname'].isna().sum())

0

In [60]:
df = df.drop(['Order Zipcode','Product Description','Customer Email','Customer Password','Product Image','Category Id','Product Category Id','Department Id','Product Status'], axis=1)
print(df)

            Type  Days for shipping (real)  Days for shipment (scheduled)  \
0          DEBIT                         3                              4
1       TRANSFER                         5                              4
2           CASH                         4                              4
3          DEBIT                         3                              4
4        PAYMENT                         2                              4
...          ...                       ...                            ...
180514      CASH                         4                              4
180515     DEBIT                         3                              2
180516  TRANSFER                         5                              4
180517   PAYMENT                         3                              4
180518   PAYMENT                         4                              4

        Benefit per order  Sales per customer   Delivery Status  \
0               91.250000          314.640015  Advance shipping
1             -249.089996          311.359985     Late delivery
2             -247.779999          309.720001  Shipping on time
3               22.860001          304.809998  Advance shipping
4              134.210007          298.250000  Advance shipping
...                   ...                 ...               ...
180514          40.000000          399.980011  Shipping on time
180515        -613.770019          395.980011     Late delivery
180516         141.110001          391.980011     Late delivery
180517         186.229996          387.980011  Advance shipping
180518         168.949997          383.980011  Shipping on time

        Late_delivery_risk   Category Name Customer City Customer Country  \
0                        0  Sporting Goods        Caguas      Puerto Rico
1                        1  Sporting Goods        Caguas      Puerto Rico
2                        0  Sporting Goods      San Jose          EE. UU.
3                        0  Sporting Goods   Los Angeles          EE. UU.
4                        0  Sporting Goods        Caguas      Puerto Rico
...                    ...             ...           ...              ...
180514                   0         Fishing      Brooklyn          EE. UU.
180515                   1         Fishing   Bakersfield          EE. UU.
180516                   1         Fishing       Bristol          EE. UU.
180517                   0         Fishing        Caguas      Puerto Rico
180518                   0         Fishing        Caguas      Puerto Rico

       Customer Fname  Customer Id Customer Lname Customer Segment  \
0               Cally        20755       Holloway         Consumer
1               Irene        19492           Luna         Consumer
2             Gillian        19491      Maldonado         Consumer
3                Tana        19490           Tate      Home Office
4                Orli        19489      Hendricks        Corporate
...               ...          ...            ...              ...
180514          Maria         1005       Peterson      Home Office
180515         Ronald         9141          Clark        Corporate
180516           John          291          Smith        Corporate
180517           Mary         2813          Smith         Consumer
180518         Andrea         7547         Ortega         Consumer

       Customer State             Customer Street  Customer Zipcode  \
0                  PR    5365 Noble Nectar Island             725.0
1                  PR            2679 Rustic Loop             725.0
2                  CA        8510 Round Bear Gate           95125.0
3                  CA             3200 Amber Bend           90027.0
4                  PR    8671 Iron Anchor Corners             725.0
...               ...                         ...               ...
180514             NY            1322 Broad Glade           11207.0
180515             CA       7330 Broad Apple Moor           93304.0
180516             CT          97 Burning Landing            6010.0
180517             PR  2585 Silent Autumn Landing             725.0
180518             PR           697 Little Meadow             725.0

       Department Name   Latitude   Longitude        Market  Order City  \
0              Fitness  18.251453  -66.037056  Pacific Asia      Bekasi
1              Fitness  18.279451  -66.037064  Pacific Asia     Bikaner
2              Fitness  37.292233 -121.881279  Pacific Asia     Bikaner
3              Fitness  34.125946 -118.291016  Pacific Asia  Townsville
4              Fitness  18.253769  -66.037048  Pacific Asia  Townsville
...                ...        ...         ...           ...         ...
180514        Fan Shop  40.640930  -73.942711  Pacific Asia    Shanghái
180515        Fan Shop  35.362545 -119.018700  Pacific Asia    Hirakata
180516        Fan Shop  41.629959  -72.967155  Pacific Asia    Adelaide
180517        Fan Shop  18.213350  -66.370575  Pacific Asia    Adelaide
180518        Fan Shop  18.290380  -66.370613  Pacific Asia   Nagercoil

       Order Country  Order Customer Id order date (DateOrders)  Order Id  \
0          Indonesia              20755         1/31/2018 22:56     77202
1              India              19492         1/13/2018 12:27     75939
2              India              19491         1/13/2018 12:06     75938
3          Australia              19490         1/13/2018 11:45     75937
4          Australia              19489         1/13/2018 11:24     75936
...              ...                ...                     ...       ...
180514         China               1005          1/16/2016 3:40     26043
180515         Japón               9141          1/16/2016 1:34     26037
180516     Australia                291         1/15/2016 21:00     26024
180517     Australia               2813         1/15/2016 20:18     26022
180518         India               7547         1/15/2016 18:54     26018

        Order Item Cardprod Id  Order Item Discount  Order Item Discount Rate  \
0                         1360            13.110000                      0.04
1                         1360            16.389999                      0.05
2                         1360            18.030001                      0.06
3                         1360            22.940001                      0.07
4                         1360            29.500000                      0.09
...                        ...                  ...                       ...
180514                    1004             0.000000                      0.00
180515                    1004             4.000000                      0.01
180516                    1004             8.000000                      0.02
180517                    1004            12.000000                      0.03
180518                    1004            16.000000                      0.04

        Order Item Id  Order Item Product Price  Order Item Profit Ratio  \
0              180517                327.750000                     0.29
1              179254                327.750000                    -0.80
2              179253                327.750000                    -0.80
3              179252                327.750000                     0.08
4              179251                327.750000                     0.45
...               ...                       ...                      ...
180514          65177                399.980011                     0.10
180515          65161                399.980011                    -1.55
180516          65129                399.980011                     0.36
180517          65126                399.980011                     0.48
180518          65113                399.980011                     0.44

        Order Item Quantity       Sales  Order Item Total  \
0                         1  327.750000        314.640015
1                         1  327.750000        311.359985
2                         1  327.750000        309.720001
3                         1  327.750000        304.809998
4                         1  327.750000        298.250000
...                     ...         ...               ...
180514                    1  399.980011        399.980011
180515                    1  399.980011        395.980011
180516                    1  399.980011        391.980011
180517                    1  399.980011        387.980011
180518                    1  399.980011        383.980011

        Order Profit Per Order    Order Region        Order State  \
0                    91.250000  Southeast Asia    Java Occidental
1                  -249.089996      South Asia           Rajastán
2                  -247.779999      South Asia           Rajastán
3                    22.860001         Oceania         Queensland
4                   134.210007         Oceania         Queensland
...                        ...             ...                ...
180514               40.000000    Eastern Asia           Shanghái
180515             -613.770019    Eastern Asia              Osaka
180516              141.110001         Oceania  Australia del Sur
180517              186.229996         Oceania  Australia del Sur
180518              168.949997      South Asia         Tamil Nadu

           Order Status  Product Card Id  \
0              COMPLETE             1360
1               PENDING             1360
2                CLOSED             1360
3              COMPLETE             1360
4       PENDING_PAYMENT             1360
...                 ...              ...
180514           CLOSED             1004
180515         COMPLETE             1004
180516          PENDING             1004
180517  PENDING_PAYMENT             1004
180518  PENDING_PAYMENT             1004

                                     Product Name  Product Price  \
0                                    Smart watch      327.750000
1                                    Smart watch      327.750000
2                                    Smart watch      327.750000
3                                    Smart watch      327.750000
4                                    Smart watch      327.750000
...                                           ...            ...
180514  Field & Stream Sportsman 16 Gun Fire Safe     399.980011
180515  Field & Stream Sportsman 16 Gun Fire Safe     399.980011
180516  Field & Stream Sportsman 16 Gun Fire Safe     399.980011
180517  Field & Stream Sportsman 16 Gun Fire Safe     399.980011
180518  Field & Stream Sportsman 16 Gun Fire Safe     399.980011

       shipping date (DateOrders)   Shipping Mode
0                 2/03/2018 22:56  Standard Class
1                 1/18/2018 12:27  Standard Class
2                 1/17/2018 12:06  Standard Class
3                 1/16/2018 11:45  Standard Class
4                 1/15/2018 11:24  Standard Class
...                           ...             ...
180514             1/20/2016 3:40  Standard Class
180515             1/19/2016 1:34    Second Class
180516            1/20/2016 21:00  Standard Class
180517            1/18/2016 20:18  Standard Class
180518            1/19/2016 18:54  Standard Class

[180519 rows x 44 columns]

In [61]:
df.describe(include='all')

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Name,Product Price,shipping date (DateOrders),Shipping Mode
count,180519,180519.000000,180519.000000,180519.000000,180519.000000,180519,180519.000000,180519,180519,180519,180519,180519.000000,180519,180519,180519,180519,180516.000000,180519,180519.000000,180519.000000,180519,180519,180519,180519.000000,180519,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519,180519,180519,180519.000000,180519,180519.000000,180519,180519
unique,4,NaN,NaN,NaN,NaN,4,NaN,50,563,2,782,NaN,1109,3,46,7458,NaN,11,NaN,NaN,5,3597,164,NaN,65752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,1089,9,NaN,118,NaN,63701,4
top,DEBIT,NaN,NaN,NaN,NaN,Late delivery,NaN,Cleats,Caguas,EE. UU.,Mary,NaN,Smith,Consumer,PR,9126 Wishing Expressway,NaN,Fan Shop,NaN,NaN,LATAM,Santo Domingo,Estados Unidos,NaN,10/25/2016 14:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Central America,Inglaterra,COMPLETE,NaN,Perfect Fitness Perfect Rip Deck,NaN,5/09/2015 18:02,Standard Class
freq,69295,NaN,NaN,NaN,NaN,98977,NaN,24551,66770,111146,65150,NaN,64112,93504,69373,122,NaN,66861,NaN,NaN,51594,2211,24840,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28341,6722,59491,NaN,24515,NaN,10,107752
mean,NaN,3.497654,2.931847,21.974989,183.107609,NaN,0.548291,NaN,NaN,NaN,NaN,6691.379495,NaN,NaN,NaN,NaN,35921.126914,NaN,29.719955,-84.915675,NaN,NaN,NaN,6691.379495,NaN,36221.894903,692.509764,20.664741,0.101668,90260.000000,141.232550,0.120647,2.127638,203.772096,183.107609,21.974989,NaN,NaN,NaN,692.509764,NaN,141.232550,NaN,NaN
std,NaN,1.623722,1.374449,104.433526,120.043670,NaN,0.497664,NaN,NaN,NaN,NaN,4162.918106,NaN,NaN,NaN,NaN,37542.461122,NaN,9.813646,21.433241,NaN,NaN,NaN,4162.918106,NaN,21045.379569,336.446807,21.800901,0.070415,52111.490959,139.732492,0.466796,1.453451,132.273077,120.043670,104.433526,NaN,NaN,NaN,336.446807,NaN,139.732492,NaN,NaN
min,NaN,0.000000,0.000000,-4274.979980,7.490000,NaN,0.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,603.000000,NaN,-33.937553,-158.025986,NaN,NaN,NaN,1.000000,NaN,1.000000,19.000000,0.000000,0.000000,1.000000,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.979980,NaN,NaN,NaN,19.000000,NaN,9.990000,NaN,NaN
25%,NaN,2.000000,2.000000,7.000000,104.379997,NaN,0.000000,NaN,NaN,NaN,NaN,3258.500000,NaN,NaN,NaN,NaN,725.000000,NaN,18.265432,-98.446312,NaN,NaN,NaN,3258.500000,NaN,18057.000000,403.000000,5.400000,0.040000,45130.500000,50.000000,0.080000,1.000000,119.980003,104.379997,7.000000,NaN,NaN,NaN,403.000000,NaN,50.000000,NaN,NaN
50%,NaN,3.000000,4.000000,31.520000,163.990005,NaN,1.000000,NaN,NaN,NaN,NaN,6457.000000,NaN,NaN,NaN,NaN,19380.000000,NaN,33.144863,-76.847908,NaN,NaN,NaN,6457.000000,NaN,36140.000000,627.000000,14.000000,0.100000,90260.000000,59.990002,0.270000,1.000000,199.919998,163.990005,31.520000,NaN,NaN,NaN,627.000000,NaN,59.990002,NaN,NaN
75%,NaN,5.000000,4.000000,64.800003,247.399994,NaN,1.000000,NaN,NaN,NaN,NaN,9779.000000,NaN,NaN,NaN,NaN,78207.000000,NaN,39.279617,-66.370583,NaN,NaN,NaN,9779.000000,NaN,54144.000000,1004.000000,29.990000,0.160000,135389.500000,199.990005,0.360000,3.000000,299.950012,247.399994,64.800003,NaN,NaN,NaN,1004.000000,NaN,199.990005,NaN,NaN
max,NaN,6.000000,4.000000,911.799988,1939.989990,NaN,1.000000,NaN,NaN,NaN,NaN,20757.000000,NaN,NaN,NaN,NaN,99205.000000,NaN,48.781933,115.263077,NaN,NaN,NaN,20757.000000,NaN,77204.000000,1363.000000,500.000000,0.250000,180519.000000,1999.989990,0.500000,5.000000,1999.989990,1939.989990,911.799988,NaN,NaN,NaN,1363.000000,NaN,1999.989990,NaN,NaN

In [62]:
df.isnull().sum()

Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Delivery Status                  0
Late_delivery_risk               0
Category Name                    0
Customer City                    0
Customer Country                 0
Customer Fname                   0
Customer Id                      0
Customer Lname                   0
Customer Segment                 0
Customer State                   0
Customer Street                  0
Customer Zipcode                 3
Department Name                  0
Latitude                         0
Longitude                        0
Market                           0
Order City                       0
Order Country                    0
Order Customer Id                0
order date (DateOrders)          0
Order Id                         0
Order Item Cardprod Id           0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Id                    0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Item Total                 0
Order Profit Per Order           0
Order Region                     0
Order State                      0
Order Status                     0
Product Card Id                  0
Product Name                     0
Product Price                    0
shipping date (DateOrders)       0
Shipping Mode                    0
dtype: int64

In [63]:
df['Customer Zipcode'] = df['Customer Zipcode'].fillna(df['Customer Zipcode'].mean())

In [64]:
df.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Name,Product Price,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725.0,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,1360,Smart watch,327.75,2/03/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,725.0,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,1360,Smart watch,327.75,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,95125.0,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,1360,Smart watch,327.75,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,90027.0,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,1360,Smart watch,327.75,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,725.0,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,1360,Smart watch,327.75,1/15/2018 11:24,Standard Class
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,Sporting Goods,Tonawanda,EE. UU.,Kimberly,19488,Flowers,Consumer,NY,2122 Hazy Corner,14150.0,Fitness,43.013969,-78.879066,Pacific Asia,Toowoomba,Australia,19488,1/13/2018 11:03,75935,1360,32.779999,0.10,179250,327.75,0.06,1,327.75,294.980011,18.580000,Oceania,Queensland,CANCELED,1360,Smart watch,327.75,1/19/2018 11:03,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Constance,19487,Terrell,Home Office,PR,1879 Green Pine Bank,725.0,Fitness,18.242538,-66.037056,Pacific Asia,Guangzhou,China,19487,1/13/2018 10:42,75934,1360,39.330002,0.12,179249,327.75,0.33,1,327.75,288.420013,95.180000,Eastern Asia,Guangdong,COMPLETE,1360,Smart watch,327.75,1/15/2018 10:42,First Class
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,Sporting Goods,Miami,EE. UU.,Erica,19486,Stevens,Corporate,FL,7595 Cotton Log Row,33162.0,Fitness,25.928869,-80.162872,Pacific Asia,Guangzhou,China,19486,1/13/2018 10:21,75933,1360,42.610001,0.13,179248,327.75,0.24,1,327.75,285.140015,68.430000,Eastern Asia,Guangdong,PROCESSING,1360,Smart watch,327.75,1/15/2018 10:21,First Class
8,CASH,3,2,133.720001,278.589996,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Nichole,19485,Olsen,Corporate,PR,2051 Dusty Route,725.0,Fitness,18.233223,-66.037056,Pacific Asia,Guangzhou,China,19485,1/13/2018 10:00,75932,1360,49.160000,0.15,179247,327.75,0.48,1,327.75,278.589996,133.720001,Eastern Asia,Guangdong,CLOSED,1360,Smart watch,327.75,1/16/2018 10:00,Second Class
9,CASH,2,1,132.149994,275.309998,Late delivery,1,Sporting Goods,San Ramon,EE. UU.,Oprah,19484,Delacruz,Corporate,CA,9139 Blue Blossom Court,94583.0,Fitness,37.773991,-121.966629,Pacific Asia,Guangzhou,China,19484,1/13/2018 9:39,75931,1360,52.439999,0.16,179246,327.75,0.48,1,327.75,275.309998,132.149994,Eastern Asia,Guangdong,CLOSED,1360,Smart watch,327.75,1/15/2018 9:39,First Class

In [65]:
df.dtypes

Type                                 str
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                      str
Late_delivery_risk                 int64
Category Name                        str
Customer City                        str
Customer Country                     str
Customer Fname                       str
Customer Id                        int64
Customer Lname                       str
Customer Segment                     str
Customer State                       str
Customer Street                      str
Customer Zipcode                 float64
Department Name                      str
Latitude                         float64
Longitude                        float64
Market                               str
Order City                           str
Order Country                        str
Order Customer Id                  int64
order date (DateOrders)              str
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                         str
Order State                          str
Order Status                         str
Product Card Id                    int64
Product Name                         str
Product Price                    float64
shipping date (DateOrders)           str
Shipping Mode                        str
dtype: object

In [66]:
df['order date (DateOrders)'] = pd.to_datetime(df['order date (DateOrders)'])
df['shipping date (DateOrders)'] = pd.to_datetime(df['shipping date (DateOrders)'])
df.dtypes

Type                                        str
Days for shipping (real)                  int64
Days for shipment (scheduled)             int64
Benefit per order                       float64
Sales per customer                      float64
Delivery Status                             str
Late_delivery_risk                        int64
Category Name                               str
Customer City                               str
Customer Country                            str
Customer Fname                              str
Customer Id                               int64
Customer Lname                              str
Customer Segment                            str
Customer State                              str
Customer Street                             str
Customer Zipcode                        float64
Department Name                             str
Latitude                                float64
Longitude                               float64
Market                                      str
Order City                                  str
Order Country                               str
Order Customer Id                         int64
order date (DateOrders)          datetime64[us]
Order Id                                  int64
Order Item Cardprod Id                    int64
Order Item Discount                     float64
Order Item Discount Rate                float64
Order Item Id                             int64
Order Item Product Price                float64
Order Item Profit Ratio                 float64
Order Item Quantity                       int64
Sales                                   float64
Order Item Total                        float64
Order Profit Per Order                  float64
Order Region                                str
Order State                                 str
Order Status                                str
Product Card Id                           int64
Product Name                                str
Product Price                           float64
shipping date (DateOrders)       datetime64[us]
Shipping Mode                               str
dtype: object

In [67]:
df['Order Year'] = df['order date (DateOrders)'].dt.year

df['Order Month'] = df['order date (DateOrders)'].dt.month

df['Order Quarter'] = df['order date (DateOrders)'].dt.quarter

df['Order Week'] = (df['order date (DateOrders)'].dt.isocalendar().week)

# Shipping Delay = actual - scheduled
df['Shipping Delay'] = (df['Days for shipping (real)']- df['Days for shipment (scheduled)'])

# 1 = on time/early, 0 = late
df['On_Time_Delivery'] = (df['Days for shipping (real)']<= df['Days for shipment (scheduled)']).astype(int)

# Profit Margin (%) of individual order
df['Profit Margin'] = (df['Order Profit Per Order']/ df['Sales']) * 100

In [68]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Name,Product Price,shipping date (DateOrders),Shipping Mode,Order Year,Order Month,Order Quarter,Order Week,Shipping Delay,On_Time_Delivery,Profit Margin
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725.0,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,2018-01-31 22:56:00,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,1360,Smart watch,327.75,2018-02-03 22:56:00,Standard Class,2018,1,1,5,-1,1,27.841342
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,725.0,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,2018-01-13 12:27:00,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,1360,Smart watch,327.75,2018-01-18 12:27:00,Standard Class,2018,1,1,2,1,0,-75.999999
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,95125.0,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,2018-01-13 12:06:00,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,1360,Smart watch,327.75,2018-01-17 12:06:00,Standard Class,2018,1,1,2,0,1,-75.600305
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,90027.0,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,2018-01-13 11:45:00,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,1360,Smart watch,327.75,2018-01-16 11:45:00,Standard Class,2018,1,1,2,-1,1,6.974829
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,725.0,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,2018-01-13 11:24:00,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,1360,Smart watch,327.75,2018-01-15 11:24:00,Standard Class,2018,1,1,2,-2,1,40.948896

In [69]:
df.to_csv(
    r'D:\05_PROJECTS\supplychain\Supply Chain Intelligence Platform for Forecasting, Logistics, and Operational Analytics\cleaned_supplychain.csv',
    index=False
)

df.to_parquet(
    r'D:\05_PROJECTS\supplychain\Supply Chain Intelligence Platform for Forecasting, Logistics, and Operational Analytics\cleaned_supplychain.parquet',
    index=False
)